sudo: required
services:
  - docker
language: node_js
node_js:
  - "11"
install:
  - curl -sL https://taskfile.dev/install.sh | sh
before_script:
  - npm install
script:
  - npm run build
  - |
    if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];
      then
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      ./bin/task build push;
    fi
